import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>
          CPay | Secure solana wallet making the world of web3 accessible to
          all.
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1>CryptoPay</h1>
      <Link href="/intro"><button className="btn">Start Now</button></Link>
    </div>
  );
}
