import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>
          CPay | Secure solana wallet making the world of web3 accessible to
          all.
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      ehll
    </div>
  );
}
